### ISSUE TITLE
Installed but crashed

### ISSUE THREAD

**Issue by egrapa** [Arthaey/anki-tag-tweaks#1]
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/webview.pyc", line 152, in _linkHandler
  File "aqt/toolbar.pyc", line 74, in _linkHandler
  File "aqt/toolbar.pyc", line 91, in _browseLinkHandler
  File "aqt/main.pyc", line 709, in onBrowse
  File "aqt/__init__.pyc", line 61, in open
  File "aqt/browser.pyc", line 364, in **init**
  File "aqt/browser.pyc", line 740, in setupTree
  File "aqt/browser.pyc", line 752, in buildTree
  File "anki/hooks.pyc", line 56, in repl
  File "/Users/xxxxx/Documents/Anki/addons/Tag_Tweaks.py", line 20, in _collapseSearchesByDefault
    searches = root.findItems(_("My Searches"), Qt.MatchFixedString)[0]
IndexError: list index out of range

**Comment by Arthaey** [comment]
Thanks for the bug report; sorry about the crash! I've updated it so it won't crash, at least.

Do you actually have a "My Searches" section in your browser? Is the interface in English?

What version of Anki are you running? What OS & version are you on?

**Comment by egrapa** [comment]
Version:
Version 2.0.32
Qt 4.8.2 PyQt 4.9.4

On Mac OS X Yosemite 10.10.4

Have Hierarchical tags

Interface English 

No "My Searches"

**Comment by Arthaey** [comment]
I didn't even know you could not have a "My Searches" section! Perhaps it's because you have zero searches, and it would appear once you did your first search?

If that's the case, then this fix is the correct one.
